name: Build CI [Linux]

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Example
        run: |
          mkdir dist
          g++ -Wall -Wpedantic -Weffc++ -std=c++23 -o dist/basic_example examples/basic_example.cpp src/*.cpp -Iinclude
          g++ -Wall -Wpedantic -Weffc++ -std=c++23 -o dist/instruction_injection examples/instruction_injection.cpp src/*.cpp -Iinclude   
          g++ -Wall -Wpedantic -Weffc++ -std=c++23 -o dist/memory_example examples/memory_example.cpp src/*.cpp -Iinclude
